# Production image for the VishwaGuru API.
#
# Two stages so build tooling (compilers for psycopg2, Pillow, numpy) never
# reaches the runtime image. Dependencies install from the committed lockfile,
# so an image built today and one built in six months contain the same
# packages -- backend/requirements.txt is generated by uv, not hand-edited.

# ---------- build ----------
FROM python:3.12-slim AS build

ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

# Build-time only: headers and compilers for the wheels that lack a manylinux
# build for this platform.
RUN apt-get update \
 && apt-get install --no-install-recommends -y \
      build-essential \
      libpq-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY backend/requirements.txt ./requirements.txt

RUN python -m venv /opt/venv \
 && /opt/venv/bin/pip install --upgrade pip \
 && /opt/venv/bin/pip install -r requirements.txt

# ---------- runtime ----------
FROM python:3.12-slim AS runtime

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PATH="/opt/venv/bin:$PATH" \
    # Repo root, not backend/. Putting backend/ on the path lets `models` and
    # `backend.models` load as two separate modules, which double-registers
    # every SQLAlchemy table and makes backend.main fail at import.
    PYTHONPATH=/app

# libmagic is required by python-magic for upload type sniffing; libpq5 is the
# psycopg2 runtime. Neither pulls in a compiler.
RUN apt-get update \
 && apt-get install --no-install-recommends -y \
      libmagic1 \
      libpq5 \
      curl \
 && rm -rf /var/lib/apt/lists/*

# Never run the service as root.
RUN useradd --create-home --uid 10001 vishwaguru

COPY --from=build /opt/venv /opt/venv

WORKDIR /app
COPY --chown=vishwaguru:vishwaguru backend/ ./backend/
COPY --chown=vishwaguru:vishwaguru data/ ./data/

# The SQLite fallback and uploaded images both write here.
RUN mkdir -p /app/data/uploads && chown -R vishwaguru:vishwaguru /app/data

USER vishwaguru

EXPOSE 8000

# Matches render.yaml's healthCheckPath. This endpoint is exempt from rate
# limiting so a busy service is never mistaken for an unhealthy one.
HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
  CMD curl -fsS http://127.0.0.1:8000/health || exit 1

# One worker by default. The Telegram poller is off unless RUN_TELEGRAM_BOT is
# set, so this image can be scaled horizontally; run exactly one separate
# instance with the flag set to serve the bot.
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
