"""baseline schema

Revision ID: 67dd0262a3fd
Revises:
Create Date: 2026-08-19 19:03:41.216426

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.models  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "67dd0262a3fd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("upvotes", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("action_plan", backend.models.JSONEncodedDict(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issues_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_reference_id"), ["reference_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_issues_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_issues_status_lat_lon", ["status", "latitude", "longitude"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_issues_upvotes"), ["upvotes"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_user_email"), ["user_email"], unique=False)

    op.create_table(
        "jurisdictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("LOCAL", "DISTRICT", "STATE", "NATIONAL", name="jurisdictionlevel"),
            nullable=False,
        ),
        sa.Column("geographic_coverage", backend.models.JSONEncodedDict(), nullable=False),
        sa.Column("responsible_authority", sa.String(), nullable=False),
        sa.Column("default_sla_hours", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jurisdictions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jurisdictions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jurisdictions_level"), ["level"], unique=False)

    op.create_table(
        "sla_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severitylevel"),
            nullable=False,
        ),
        sa.Column(
            "jurisdiction_level",
            sa.Enum("LOCAL", "DISTRICT", "STATE", "NATIONAL", name="jurisdictionlevel"),
            nullable=False,
        ),
        sa.Column("department", sa.String(), nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sla_configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sla_configs_department"), ["department"], unique=False)
        batch_op.create_index(batch_op.f("ix_sla_configs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sla_configs_jurisdiction_level"), ["jurisdiction_level"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sla_configs_severity"), ["severity"], unique=False)

    op.create_table(
        "grievances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severitylevel"),
            nullable=False,
        ),
        sa.Column("pincode", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("district", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("current_jurisdiction_id", sa.Integer(), nullable=False),
        sa.Column("assigned_authority", sa.String(), nullable=False),
        sa.Column("sla_deadline", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "ESCALATED", "RESOLVED", name="grievancestatus"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_jurisdiction_id"],
            ["jurisdictions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grievances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_grievances_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_latitude"), ["latitude"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_longitude"), ["longitude"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_grievances_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_grievances_status_jurisdiction", ["status", "current_jurisdiction_id"], unique=False
        )
        batch_op.create_index(
            "ix_grievances_status_lat_lon", ["status", "latitude", "longitude"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_grievances_unique_id"), ["unique_id"], unique=True)

    op.create_table(
        "escalation_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grievance_id", sa.Integer(), nullable=False),
        sa.Column("previous_authority", sa.String(), nullable=False),
        sa.Column("new_authority", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum("SLA_BREACH", "SEVERITY_UPGRADE", "MANUAL", name="escalationreason"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grievance_id"],
            ["grievances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("escalation_audits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_escalation_audits_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_escalation_audits_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "grievance_followers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grievance_id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("integrity_hash", sa.String(), nullable=False),
        sa.Column("previous_integrity_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grievance_id"],
            ["grievances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grievance_followers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_follower_grievance_email", ["grievance_id", "user_email"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_grievance_followers_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_grievance_followers_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_grievance_followers_integrity_hash"), ["integrity_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_grievance_followers_user_email"), ["user_email"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grievance_followers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grievance_followers_user_email"))
        batch_op.drop_index(batch_op.f("ix_grievance_followers_integrity_hash"))
        batch_op.drop_index(batch_op.f("ix_grievance_followers_id"))
        batch_op.drop_index(batch_op.f("ix_grievance_followers_created_at"))
        batch_op.drop_index("ix_follower_grievance_email")

    op.drop_table("grievance_followers")
    with op.batch_alter_table("escalation_audits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_escalation_audits_timestamp"))
        batch_op.drop_index(batch_op.f("ix_escalation_audits_id"))

    op.drop_table("escalation_audits")
    with op.batch_alter_table("grievances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grievances_unique_id"))
        batch_op.drop_index("ix_grievances_status_lat_lon")
        batch_op.drop_index("ix_grievances_status_jurisdiction")
        batch_op.drop_index(batch_op.f("ix_grievances_status"))
        batch_op.drop_index(batch_op.f("ix_grievances_severity"))
        batch_op.drop_index(batch_op.f("ix_grievances_longitude"))
        batch_op.drop_index(batch_op.f("ix_grievances_latitude"))
        batch_op.drop_index(batch_op.f("ix_grievances_id"))
        batch_op.drop_index(batch_op.f("ix_grievances_created_at"))
        batch_op.drop_index(batch_op.f("ix_grievances_category"))

    op.drop_table("grievances")
    with op.batch_alter_table("sla_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sla_configs_severity"))
        batch_op.drop_index(batch_op.f("ix_sla_configs_jurisdiction_level"))
        batch_op.drop_index(batch_op.f("ix_sla_configs_id"))
        batch_op.drop_index(batch_op.f("ix_sla_configs_department"))

    op.drop_table("sla_configs")
    with op.batch_alter_table("jurisdictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jurisdictions_level"))
        batch_op.drop_index(batch_op.f("ix_jurisdictions_id"))

    op.drop_table("jurisdictions")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_user_email"))
        batch_op.drop_index(batch_op.f("ix_issues_upvotes"))
        batch_op.drop_index("ix_issues_status_lat_lon")
        batch_op.drop_index(batch_op.f("ix_issues_status"))
        batch_op.drop_index(batch_op.f("ix_issues_source"))
        batch_op.drop_index(batch_op.f("ix_issues_reference_id"))
        batch_op.drop_index(batch_op.f("ix_issues_id"))
        batch_op.drop_index(batch_op.f("ix_issues_created_at"))
        batch_op.drop_index(batch_op.f("ix_issues_category"))

    op.drop_table("issues")
    # ### end Alembic commands ###
